# generate a 16:9 image. the resolution starts at 16*8x9*8. this 
# is because the diffuser expects each dimension of the resolution
# to be divisible by 8. any scale, N, will result in a resolution
# 16*8*N x 9*8*N  for a 1920x1080 image set scale to 15.
wide:
  enabled: false
  scale: 15

# same as wide but with the ratio swapped
tall:
  enabled: false
  scale: 15

# starts at 8x8 scale multiplies from there
# scale 64 is the default 512x512 resolution
square:
  enabled: true
  scale: 128

# set the height and width manually, generation will fail if either
# dimension is not divisible by 8.
manual_resolution:
  enabled: false
  height: 512
  width: 512

# each pass will double the height and width of the image
upscale:
  enabled: true
  passes: 1

# which diffusers to use for generation. options are
# protogen, dream2, epic, dream1, er, lowpoly,
# sci-fi, nitro, sd2, waifu, redshift
diffusers:
  - 'er'
  - 'protogen'
  - 'dream2'
  - 'epic'


# any number of prompts can go here, each prompt is limited to 77 tokens.
prompts:
  - 'Design a majestic Lovecraftian-steampunk airship in late Victorian style. Tapered hull, large size, and skyward scene. Four steam-powered pylons with purple aura. Emphasize pipes, valves, and subtle gears. Focus on awe-inspiring, pre-horror introduction'

# this will tell the diffuser to avoid certain things
negative_prompts:
  - 'water, balloons, too many gears, gloomy visuals'
  
# the number of images to generate per prompt
count: 3

# Increases VRAM substantially but generates much faster when true 
fast: false

# enable this to fix the seed. One diffuser with the same seed will produce
# identical images each time it is run. This is useful for refining a prompt
manual_seed:
  enabled: false
  seed: 5642398

# enable this to blackout any potentially NSFW images generated.
safety_check:
  enabled: false
  # some diffusers do not support safety checking. if you get an error
  # for a diffuser when you enable this, add it to the list below
  exempt_diffusers:
    - 'dream1'
    - 'dream2'
    - 'sci-fi'
    - 'redshift'

# where to save the generated images to. Regardless of the directory, it
# will create a subdir with the date, then a subdir with the time, then a
# subdir with the diffuser, then each image generated by that diffuser
# will be placed in that directory. The date and time are set based on when
# the command is issued not when the image is generated
output_path: './output'

# pauses image generation if the GPU temp is above the threshhold,
# resumes when GPU hits the target temperature. This will not stop
# generation but will wait between generations.
cooldown:
  enabled: true
  # temperature units are ºC
  threshhold: 75
  # the temparature to wait until the GPU cools to before resuming generation tasks.
  resume_temp: 70

